# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppCenterPOC' do
  pod 'AppCenter/Crashes', '~> 1.11.0'
  pod 'AppCenterReactNativeShared', '~> 1.10.0'
  pod 'AppCenter/Analytics', '~> 1.11.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppCenterPOC

  

  platform :ios, '9.0'
  target 'AppCenterPOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AppCenterPOC-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppCenterPOC-tvOS

  target 'AppCenterPOC-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
